sonar.projectKey=SwiftNotes
sonar.projectName=SwiftNotes
sonar.sources=frontend/src,backend
sonar.tests=frontend/src/__tests__,backend/tests
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx
sonar.coverage.exclusions=**/Landing.jsx,**/AddNoteButton.jsx,**/WelcomeBanner.jsx,**/EditorToolbar.jsx,**/NoteEditor.jsx,**/ProtectedRoute.jsx,**/AuthContext.jsx,**/axios.js,**/routes/**,**/middlewares/**,**/db.js,**/index.js,**/main.jsx,**/App.jsx
sonar.sourceEncoding=UTF-8