sonar.projectKey=notes-app
sonar.projectName=Notes App
sonar.sources=frontend/src,backend
sonar.tests=frontend/src/__tests__,backend/tests
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx